spring.application.name=Portfolio

server.port=8080
spring.datasource.url=jdbc:mysql://localhost/portfolio
spring.datasource.username=root
spring.datasource.password=Viraj123@

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
